/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import { type NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";

export const config = {
  runtime: "experimental-edge",
};

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
  const { data, isLoading, error } = useSWR(() => "/api/hello", fetcher);

  if (error) return <div>Error...</div>;
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>No data...</div>;

  return (
    <>
      <Head>
        <title>Testing Server Call</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            The name is:{" "}
            <span className="text-[hsl(280,100%,70%)]">{data.name}</span>
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
