#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n 🚀 Running pre-push hook...\n"

echo "🔎  Checking for storybook changes..."

# Get the name of the current branch
current_branch=$(git symbolic-ref --short HEAD)

# Run git diff to check if any files were changed in src/modules
if git diff --name-only HEAD | grep -q '^src/modules/'; then
  echo "🎨 Changes found in src/modules, building Storybook..."
  pnpm build-storybook
else
  echo "🚀 No changes found in src/modules, skipping Storybook build."
fi

echo '#############
🛠️  Building for edge...
#############'

pnpm build:for-edge

exit 0
