---
name: Comment on PR

on:
  workflow_call:
    inputs:
      url:
        type: string
        required: true
      alias:
        type: string
        required: true
      environment:
        type: string
        required: true
      deployment_id:
        type: string
        required: true
jobs:
  comment:
    name: Comment on PR
    uses: raisedadead/portfolio/.github/workflows/comment.yml@main
    with:
      issue-number: ${{ github.event.pull_request.number }}
      url: ${{ inputs.url }}
      alias: ${{ inputs.alias }}
      environment: ${{ inputs.environment }}
      deployment_id: ${{ inputs.deployment_id }}
