name: OnHook - Deploy Preview
run-name: 'Deploy PR #${{ github.event.number }} Preview'

# This workflow is triggered on pull requests against the develop branch.
# This workflow is triggered on pushes to branches starting with test/

on:
  # Trigger the workflow on a push to a branch that starts with `test/`
  push:
    branches:
      - test/*
      - '!renovate/*'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - '!renovate/*'
  workflow_call:

jobs:
  deploy:
    name: Build and Deploy Project
    uses: ./.github/workflows/job-build-develop.yml
    with:
      environment: 'develop'
    secrets:
      API_PAT: ${{ secrets.API_PAT }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  e2e-tests:
    name: Run Unit and E2E Tests
    uses: ./.github/workflows/job-run-tests.yml
    needs: [deploy]
    with:
      environment: 'develop'
      url: ${{ format('{0}/', needs.deploy.outputs.url) }}
      tag_name: ${{ github.event.pull_request.head.sha }}
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

  comment:
    name: Comment on PR
    uses: ./.github/workflows/job-comment-pr.yml
    needs: [deploy]
    permissions:
      pull-requests: write
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: 'develop'
