name: Deploy main to Cloudflare Pages

# This workflow triggers when a push happens on on main
# Latest deployment: https://main.common-app-frontend.pages.dev/

on:
  push:
    branches:
      - main
      - test/pre-launch

  workflow_dispatch:

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/build-workflow.yml
    with:
      environment: 'production'
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  e2e-tests:
    name: Run e2e Tests
    uses: ./.github/workflows/e2e-workflow.yml
    with:
      environment: 'production'
    secrets:
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
