name: Preview

# This workflow is triggered on pull requests against the develop branch.
# This workflow is triggered on pushes to branches starting with test/

on:
  # Trigger the workflow on a push to a branch that starts with `test/`
  push:
    branches:
      - test/*

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Project
    uses: ./.github/workflows/workflow-build.yml
    with:
      environment: 'develop'
      tag_name: ${{ github.event.pull_request.head.sha }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  e2e-tests:
    name: Run Unit and E2E Tests
    uses: ./.github/workflows/workflow-run-tests.yml
    needs: [deploy]
    with:
      environment: 'develop'
      url: ${{ format('{0}/', needs.deploy.outputs.url) }}
      tag_name: ${{ github.event.pull_request.head.sha }}
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

  comment:
    name: Comment on PR
    uses: ./.github/workflows/workflow-comment.yml
    needs: [deploy]
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: 'develop'
