name: OnHook - Deploy Develop

# This workflow is triggered on a push to the develop branch.
# Latest deployment: https://develop.common-app-frontend.pages.dev/

on:
  push:
    branches:
      - develop
  workflow_call:

jobs:
  deploy:
    name: Build and Deploy Project
    uses: ./.github/workflows/job-build-develop.yml
    with:
      environment: 'develop'
    secrets:
      API_PAT: ${{ secrets.API_PAT }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  e2e-tests:
    name: Run Unit and E2E Tests
    uses: ./.github/workflows/job-run-tests.yml
    needs: [deploy]
    with:
      environment: 'develop'
      tag_name: ${{ github.sha }}
    secrets:
      API_PAT: ${{ secrets.API_PAT }}
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
