name: Deploy main to Cloudflare Pages

# This workflow triggers when a push happens on on main
# Latest deployment: https://main.common-app-frontend.pages.dev/

on:
  push:
    branches:
      - main
      - test/pre-launch

  workflow_dispatch:

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/build-workflow.yml
    with:
      environment: 'production'

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-workflow.yml
    needs: [build]
    with:
      environment: 'production'
      run_id: ${{needs.build.outputs.run_id}}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  comment:
    name: Comment on PR
    uses: ./.github/workflows/comment-workflow.yml
    needs: [deploy]
    with:
      url: ${{ needs.deploy.outputs.url }}
      alias: ${{ needs.deploy.outputs.alias }}
      environment: ${{ needs.deploy.outputs.environment }}
      deployment_id: ${{ needs.deploy.outputs.deployment_id }}

  e2e-tests:
    name: Run e2e Tests
    uses: ./.github/workflows/e2e-workflow.yml
    needs: [deploy]
    with:
      environment: 'production'
      url: ${{ vars.NEXT_PUBLIC_BASE_URL }}
    secrets:
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
