name: Deploy main to Cloudflare Pages

# This workflow triggers when a push happens on on main
# Latest deployment: https://main.common-app-frontend.pages.dev/

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Project
    uses: ./.github/workflows/workflow-build.yml
    with:
      environment: 'production'
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}

  e2e-tests:
    name: Run e2e Tests
    uses: ./.github/workflows/workflow-e2e.yml
    needs: [build]
    with:
      environment: 'production'
      url: ${{ vars.NEXT_PUBLIC_BASE_URL }}
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}

  deploy:
    name: Deploy
    uses: ./.github/workflows/workflow-deploy.yml
    needs: [e2e-tests]
    with:
      environment: 'production'
      run_id: ${{needs.build.outputs.run_id}}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
