name: Staging

# This workflow is triggered on a push to the develop branch.
# Latest deployment: https://staging.common-app-frontend.pages.dev/

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run e2e Tests
    uses: ./.github/workflows/e2e-workflow.yml
    with:
      environment: 'staging'
    secrets:
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      E2E_TURNSTILE_SECRET: ${{ secrets.E2E_TURNSTILE_SECRET }}

  build:
    name: Build Project
    uses: ./.github/workflows/build-workflow.yml
    needs: [e2e-tests]
    with:
      environment: 'staging'
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
