---
name: Deploy Project to Production

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: The tag to be deployed
        type: string
        required: true

jobs:
  check-tag:
    name: Check Tag Format
    uses: ./.github/workflows/job-check-tag.yml
    with:
      environment: 'production'
      tag_name: ${{ inputs.tag_name }}

  deploy:
    if: needs.check-tag.outputs.success
    needs: [check-tag]
    name: Build and Deploy Project
    uses: ./.github/workflows/job-build-release.yml
    with:
      branch_name: 'main'
      environment: 'production'
      tag_name: ${{ inputs.tag_name }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  run-tests:
    if: needs.check-tag.outputs.success
    name: Run E2E and Unit Tests
    uses: ./.github/workflows/job-run-tests.yml
    needs: ['check-tag', 'deploy']
    with:
      environment: 'production'
      tag_name: ${{ inputs.tag_name }}
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
