---
name: Job - Run E2E and Unit Tests

on:
  workflow_call:
    inputs:
      environment:
        description: environment name
        type: string
        required: true
      url:
        type: string
      tag_name:
        description: The tag to be tested
        type: string
        required: true
    secrets:
      DEBUG_MODE_SECRET:
        description: secret to bypass cloudflare
        required: true
      NEXT_PUBLIC_TEST_PASSWORD:
        description: e2e test user pwd
        required: true
      CF_ACCESS_CLIENT_SECRET:
        description: cloudflare access secret
        required: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        node-version: [18.18.0]

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Checkout Tag
        run: |
          git checkout ${{ inputs.tag_name }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Run Unit Tests
        uses: cypress-io/github-action@v6.6.1
        with:
          record: false
          component: true
        env:
          CI: true
          NEXT_PUBLIC_TURNSTILE_SITEKEY: ${{ vars.E2E_TURNSTILE_KEY }}

      - name: Run E2E Tests
        uses: cypress-io/github-action@v6.6.1
        with:
          command: pnpm e2e:ci
          record: false
        env:
          CI: true
          NEXT_PUBLIC_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          NEXT_PUBLIC_AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          NEXT_PUBLIC_BASE_URL: ${{ inputs.url || vars.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_TEST_USER: ${{ vars.NEXT_PUBLIC_TEST_USER }}
          NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
          DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
          CF_ACCESS_CLIENT_ID: ${{ vars.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
