---
name: Check Tag Format

on:
  workflow_call:
    inputs:
      tag_name:
        description: The tag name to validate
        type: string
        required: true
      environment:
        type: string
        required: true
    outputs:
      success:
        value: ${{ jobs.check.outputs.success }}
jobs:
  check:
    name: Check tag
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.19.1]

    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ inputs.environment }} == 'production' && ${{ inputs.tag_name }} =~ ^[0-9]+.[0-9]+.[0-9]+$ || ${{ inputs.environment }} == 'staging' ]]; then
              echo "success=true" >> $GITHUB_OUTPUT
          else
              echo "Passed tag does not match expected pattern for ${{ inputs.environment }}"
              echo "success=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      success: ${{ steps.check-tag.outputs.success }}
