---
name: Deploy Project to Staging

on:
  workflow_call:
    inputs:
      tag_name:
        description: The tag to be deployed
        type: string
        required: true

# TODO: Run the tests locally before we deploy to staging

jobs:
  deploy:
    name: Build and Deploy Project
    uses: ./.github/workflows/workflow-build.yml
    with:
      environment: 'staging'
      tag_name: ${{ inputs.tag_name }}
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  run-tests:
    name: Run E2E and Unit Tests
    uses: ./.github/workflows/workflow-run-tests.yml
    needs: ['deploy']
    with:
      environment: 'staging'
      tag_name: ${{ inputs.tag_name }}
    secrets:
      DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
      NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
