---
name: Run E2E Tests

on:
  workflow_call:
    inputs:
      environment:
        description: environment name
        type: string
        required: true
      url:
        type: string
        required: true
    secrets:
      DEBUG_MODE_SECRET:
        description: secret to bypass cloudflare
        required: true
      NEXT_PUBLIC_TEST_PASSWORD:
        description: e2e test user pwd
        required: true
      CF_ACCESS_CLIENT_SECRET:
        description: cloudflare access secret
        required: true

jobs:
  e2e-tests:
    name: Run e2e Tests
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    strategy:
      matrix:
        node-version: [16.19.1]

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Debug
        run: |
          echo "${{ inputs }}, ${{ vars.NEXT_PUBLIC_BASE_URL }}"

      - name: Cypress run
        uses: cypress-io/github-action@v5.7.2
        with:
          command: pnpm e2e:ci
          record: false
        env:
          CI: true
          NEXT_PUBLIC_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          NEXT_PUBLIC_AUTH0_DOMAIN: ${{ vars.AUTH0_DOMAIN }}
          NEXT_PUBLIC_AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          NEXT_PUBLIC_AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          NEXT_PUBLIC_BASE_URL: ${{ inputs.url }}
          NEXT_PUBLIC_TEST_USER: ${{ vars.NEXT_PUBLIC_TEST_USER }}
          NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
          DEBUG_MODE_SECRET: ${{ secrets.DEBUG_MODE_SECRET }}
          CF_ACCESS_CLIENT_ID: ${{ vars.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
